### PR TITLE
Implement the Cargo Shooter subsystem

### PR DESCRIPTION
**Pull request by richiksc**

### CODE REVIEW

**Comment by andrewfhou** [comment]
Make sure to edit the practice bot's .yml as well. You can do this before or after merge

**Comment by richiksc** [comment]
Ok, will edit practice bot yml before merge. Do you know when we're going to get real Talon IDs?

**Comment by andrewfhou** [comment]
Talon IDs for the practice bot will mirror the competition bot exactly. Currently unknown what talons the other subsystems will use, but we should know soon

**Comment by richiksc** [comment]
Cargo shooter configuration added to all YMLs. Also added to Zenith config so same code can run without failing on zenith, ghost talons will be used.

**Pull request merged**
