### PR TITLE
Team-specific project infrastucture for 2019

### PR DESCRIPTION
**Pull request by richiksc**
This pull request, if merged:
* Adds JUnit 5.0 and test directories
* Adds checkstyle and a checkstyle configuration
* Updates some code to satisfy checkstyle
* Adds Javadoc
* Cleans up build.gradle, declares Java Version 11
* Brings in `com.edinarobotics.utils` package.
* Brings in `checker` infrastucture for Subsystem Checking

### CODE REVIEW

**Comment by richiksc** [comment]
Hold on, have to squash some commits to clean up history

**Comment by pdeutsch** [comment]
Although I often do the same thing, it is generally not a good idea to combine a lot of things like this in one pull request.  It is easier to have one pull request for build/gradle changes, and another for the utils package, and another for the subsystems checking.  This makes it easier to review and cleanup.

I don't think we need to change it now, but in the future several smaller pull requests are generally better/easier.

I definitely think we need to go through the utils package and remove some of the extra cruft in there that we are not using, such as the Subsystem1816 and some others.

**Comment by richiksc** [comment]
@pdeutsch I think we will use Subsystem1816 more this year as it now implements the Checkable interface.

**Comment by richiksc** [comment]
Commit history cleaned up. Merging.

**Pull request merged**
